### ISSUE TITLE
`batch_execute` doesn't use provided noise model.

### ISSUE THREAD

**Issue by kshyatt-aws** [amazon-braket/amazon-braket-pennylane-plugin-python#176]
**Describe the bug**
`execute` will apply a user-provided `NoiseModel` to circuits, but `batch_execute` does not.

**To reproduce**
Run a circuit (e.g. Bell circuit) with a `BitFlip(0.5)` on all gates using `execute` and `batch_execute` - the measurement outcomes will differ substantially.

**Expected behavior**
`batch_execute` should apply the device's `NoiseModel` to all circuits in the batch.

**Screenshots or logs**
N/A.

**System information**
A description of your system. Please provide:
- **Amazon Braket Python PennyLane Plugin version**: 1.16.1
- **Amazon Braket Python SDK version**: 1.42.1
- **Amazon Braket Python Schemas version**: 1.17.0
- **Amazon Braket Python Default Simulator version**: 1.15.0
- **Python version**: 3.10

**Additional context**

**Comment by krneta** [comment]
Hi Katherine,

The issue should be fixed in [v1.19.0](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/commit/fd3b09a8368bf8c3e06207d50ff6535a601d231f)
