### ISSUE TITLE
Support `batch_execute` with `BraketLocalQubitDevice`

### ISSUE THREAD

**Issue by kshyatt-aws** [amazon-braket/amazon-braket-pennylane-plugin-python#178]
**Describe the feature you'd like**
The Braket local simulators now support `run_batch` using local CPU resources. We should allow PennyLane to hook into that functionality.

**How would this feature be used? Please describe.**
Any use case with many similar small circuits to run, for example SPSA on a 10 qubit circuit or computing a shadows-expval with 5000 shots on a 12 qubit circuit. 

**Describe alternatives you've considered**
N/A.

**Additional context**
Since both the child classes of `BraketQubitDevice` support parallelism, maybe it makes sense to move some of the logic up into the parent class?

**Comment by speller26** [comment]
Implemented in #269
