### ISSUE TITLE
Support `Prod` as observables

### ISSUE THREAD

**Issue by astralcai** [amazon-braket/amazon-braket-pennylane-plugin-python#241]
**Describe the feature you'd like**

In the latest version of PennyLane (0.36.0-dev), new opmath is enabled by default. Observables made with `@` will now be instances of `Prod` instead of `Tensor`. This will not work:
```
qml.expval(qml.PauliX(0) @ qml.PauliY(1))
```
because the pennylane-braket plugin currently do not know how to handle `Prod`.

**Solution**

In `translation.py`, add
```
@_translate_observable.register
def _(t: qml.ops.Prod):
    return reduce(lambda x, y: x @ y, [_translate_observable(factor) for factor in t.operands])
```
should make it work with new opmath.

**Comment by ashlhans** [comment]
Hi @astralcai - thank you for raising this issue! We will look into this.
