### ISSUE TITLE
Support `LinearCombination` as an observable

### ISSUE THREAD

**Issue by astralcai** [amazon-braket/amazon-braket-pennylane-plugin-python#245]
**Describe the feature you'd like**
In v0.36.0 of PennyLane, the new `LinearCombination` is used in favour of the legacy `Hamiltonian`, which should also be supported as an observable.

**Additional context**
There are two classes now to represent a Hamiltonian: `qml.ops.Hamiltonian`, and `qml.ops.LinearCombination`. The latter is now used by default in favour of the former. With new opmath enabled, `qml.Hamiltonian` will refer to `LinearCombination`, and with new opmath disabled, `qml.Hamiltonian` will refer to the old `Hamiltonian` class.

**Solution**
1. In `braket_device.py`, line 169 should be updated to `return base_observables.union({"Hamiltonian", "LinearCombination"})`
2. Update all `isinstance(..., Hamiltonian)` checks to `isinstance(..., (qml.ops.Hamiltonian, qml.ops.LinearCombination))`, such as line 230 of `braket_device.py`, line 561 and 691 of `translation.py`
3. Update line 584-585 of `translation.py` to:
```
@_translate_observable.register(qml.ops.Hamiltonian)
@_translate_observable.register(qml.ops.LinearCombination)
def _(H: Union[qml.ops.Hamiltonian, qml.ops.LinearCombination]):
    ...
```

**Comment by virajvchaudhari** [comment]
Thanks for pointing this out @astralcai, we will take a look into this.
