### ISSUE TITLE
Add PL integration test to CI

### ISSUE THREAD

**Issue by astralcai** [amazon-braket/amazon-braket-pennylane-plugin-python#254]
The current CI only contains the unit tests, but not integration tests with PennyLane. This leads to PRs passing CI but breaking compatibility with PL getting merged.

Here's the integration tests run on the PL plugin test matrix: https://github.com/PennyLaneAI/plugin-test-matrix/blob/master/.github/workflows/braket-latest-latest.yml

**Comment by astralcai** [comment]
In principle, for the plugins, we want to run CI with the latest version of PennyLane. We only verify that the latest plugin still works with stable PennyLane once a week in the test matrix.

> Is the purpose here to have better notifications on the Braket side for incoming breaking changes?

This is exactly the reason. In this release we found out that the latest braket plugin did not work with the soon-to-be-released PennyLane a week before the release, which is something that should've been caught way earlier.

**Comment by math411** [comment]
Sorry about the delay, I am getting back to this. I am getting out https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/pull/264. This will fail until the `obs` are fixed up.

**Comment by speller26** [comment]
Fixed with #264
