### ISSUE TITLE
Print noisy circuit when a Braket noise model is applied to PL device with `parallel=True`

### ISSUE THREAD

**Issue by bgupt** [amazon-braket/amazon-braket-pennylane-plugin-python#255]
PennyLane device with Braket backend supports [noise model](https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/4560f4e4dc49f621c3698b2d7eeffe6073d09fec/src/braket/pennylane_plugin/braket_device.py#L124). The noise model added to the device will automatically apply to circuit executed by the device.

Normally, one can call `print(device.circuit)` to visualize the circuit after the device has executed it. This allows users to check if the noise is applied as expected. But in the case where the `device` is set to `parallel=True`, this does not work. The underlying issue is that `batch_execute` does not populate the deivce's `circuit` field (because there are multiple circuits being executed on the device).

**Describe the feature you'd like**
If the `device` is initialized with `parallel=True`, the device should cache all of the circuits that have been run on the device so that they can be accessed later. We should also have updated documentation on how to attach a noise model to a device and how to print the resulting circuit(s).

**Describe alternatives you've considered**
The alternative is to use `parallel=False` so that only a single circuit is run and populated in the `circuit` field of the device, and then call `print(device.circuit)`.

**Comment by math411** [comment]
Hi @bgupt,

Are you looking to visualize a circuit with a noise model similar to:

```
noise_model = NoiseModel()
noise_model.add_noise(Depolarizing(0.1), GateCriteria(Gate.H))

circ = Circuit().h(0).s(1).h(2).y(0).x(1).z(2)

noisy_circ = noise_model.apply(circ)
print(noisy_circ)
```

```
>>>
T  : |     0     |1|
                    
q0 : -H-DEPO(0.1)-Y-
                    
q1 : -S-----------X-
                    
q2 : -H-DEPO(0.1)-Z-

T  : |     0     |1|
```

I can take a look at the documentation so it is clearer for visualizing and attaching noise models.

**Comment by bgupt** [comment]
I would like to print the noisy circuit during a hybrid_jobs execution. For example, look at the following code snippet. The Noise model is defined in Braket and then applied to Pennylane device. I would like to see the noisy quantum circuit that qml.device is running, which is the circuit in the objective function with noise. 

```
# Braket Noise model
noise_model = NoiseModel()
noise_model.add_noise(Depolarizing(0.1), GateCriteria(Gate.H))

# Quantum Device
qml.device("braket.local.qubit", device_arn=device_arn, parallel=True, wires=n_qubits, noise_model=noise_model)


# Define molecular Hamiltonian
def Hamiltonian(x):
    return qml.qchem.molecular_hamiltonian(symbols, x, charge=charge)[0]

#Variational Quantum Circuit
hf_state = qml.qchem.hf_state(electrons, qubits)
# generate single- and double-excitations
singles, doubles = qml.qchem.excitations(electrons, qubits)

@qml.qnode(device, interface="autograd")
def circuit(params, obs, wires):
    qml.BasisState(hf_state, wires=wires)
    qml.DoubleExcitation(params[0], wires=[0, 1, 2, 3])
    qml.DoubleExcitation(params[1], wires=[0, 1, 4, 5])

    return qml.expval(obs)

def objective(params, x):
    hamiltonian = Hamiltonian(x)
    obj = circuit(params, obs=hamiltonian, wires=range(qubits))
    # ********** Print the noisy circuit that hase noise_model applied to it! ************ #
    
    return obj

qml.GradientDescentOptimizer(stepsize=0.4).step(objective, params, x)
```

**Comment by WingCode** [comment]
Could you assign me to the issue?

**Comment by rmshaffer** [comment]
Re-opening this issue, as #270 was never merged to main.
