### ISSUE TITLE
Update the pinned version of autoray

### ISSUE THREAD

**Issue by mlxd** [amazon-braket/amazon-braket-pennylane-plugin-python#262]
https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/blob/2e78d0400d30136dff35e66af15558c1872d6a27/setup.py#L38

The upcoming version of PennyLane requires an autoray pinned to a minimum of 0.6.11 (https://github.com/PennyLaneAI/pennylane/blob/2a36a355f212ffba12c8c49d5842eef8a7c6dbdb/setup.py#L32). Currently, the hard upper-limit of 0.6.10 on this plugin causes failures within our CI due to the incompatible version resolutions (see https://github.com/PennyLaneAI/plugin-test-matrix/actions/runs/9310762656/job/25628775590). Can this package version pin be either removed to allow free movement with PennyLane, or be updated to match PennyLane's minimum version of 0.6.11.

This would involve an update to the recently merged PR https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/pull/256

**Comment by math411** [comment]
Going to work to fix that in https://github.com/amazon-braket/amazon-braket-pennylane-plugin-python/pull/263

**Comment by mlxd** [comment]
Thanks @math411  
I'll mark as closed.
